/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFramePerson.java
 *
 * Created on Dec 12, 2008, 4:03:50 PM
 */

package main;

/**
 *
 * @author francist
 */
public class JFramePerson extends javax.swing.JFrame {

    /** Creates new form JFramePerson */
    public JFramePerson() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_CourseList = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_PersonType = new javax.swing.JTextField();
        jTextField_ZipCode = new javax.swing.JTextField();
        jTextField_State = new javax.swing.JTextField();
        jTextField_City = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_PersonID = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1ResultList = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jFrame1.setName("jFrame1"); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame2.setName("jFrame2"); // NOI18N

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame3.setName("jFrame3"); // NOI18N

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog1.setName("jDialog1"); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(main.MainApp.class).getContext().getResourceMap(JFramePerson.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton_Search.setText(resourceMap.getString("jButton_Search.text")); // NOI18N
        jButton_Search.setName("jButton_Search"); // NOI18N
        jButton_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SearchMouseClicked(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton_Clear.setText(resourceMap.getString("jButton_Clear.text")); // NOI18N
        jButton_Clear.setName("jButton_Clear"); // NOI18N
        jButton_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ClearMouseClicked(evt);
            }
        });

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jLayeredPane1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jLayeredPane1.border.titleFont"))); // NOI18N
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable_CourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Section", "Meeting Times", "Location"
            }
        ));
        jTable_CourseList.setName("jTable_CourseList"); // NOI18N
        jScrollPane2.setViewportView(jTable_CourseList);
        jTable_CourseList.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable_CourseList.columnModel.title0")); // NOI18N
        jTable_CourseList.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable_CourseList.columnModel.title1")); // NOI18N
        jTable_CourseList.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable_CourseList.columnModel.title2")); // NOI18N
        jTable_CourseList.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable_CourseList.columnModel.title3")); // NOI18N

        jScrollPane2.setBounds(20, 20, 310, 160);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jLayeredPane2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jLayeredPane2.border.titleFont"))); // NOI18N
        jLayeredPane2.setName("jLayeredPane2"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setBounds(20, 80, 80, 20);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setBounds(20, 60, 80, 20);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setBounds(20, 120, 80, 20);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setBounds(20, 140, 80, 20);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setBounds(20, 160, 80, 20);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setBounds(20, 100, 80, 20);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_PersonType.setText(resourceMap.getString("jTextField_PersonType.text")); // NOI18N
        jTextField_PersonType.setName("jTextField_PersonType"); // NOI18N
        jTextField_PersonType.setBounds(110, 160, 179, 20);
        jLayeredPane2.add(jTextField_PersonType, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_ZipCode.setText(resourceMap.getString("jTextField_ZipCode.text")); // NOI18N
        jTextField_ZipCode.setName("jTextField_ZipCode"); // NOI18N
        jTextField_ZipCode.setBounds(110, 140, 179, 20);
        jLayeredPane2.add(jTextField_ZipCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_State.setText(resourceMap.getString("jTextField_State.text")); // NOI18N
        jTextField_State.setName("jTextField_State"); // NOI18N
        jTextField_State.setBounds(110, 120, 179, 20);
        jLayeredPane2.add(jTextField_State, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_City.setText(resourceMap.getString("jTextField_City.text")); // NOI18N
        jTextField_City.setName("jTextField_City"); // NOI18N
        jTextField_City.setBounds(110, 100, 179, 20);
        jLayeredPane2.add(jTextField_City, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_Address.setText(resourceMap.getString("jTextField_Address.text")); // NOI18N
        jTextField_Address.setName("jTextField_Address"); // NOI18N
        jTextField_Address.setBounds(110, 80, 179, 20);
        jLayeredPane2.add(jTextField_Address, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_LastName.setText(resourceMap.getString("jTextField_LastName.text")); // NOI18N
        jTextField_LastName.setName("jTextField_LastName"); // NOI18N
        jTextField_LastName.setBounds(110, 60, 179, 20);
        jLayeredPane2.add(jTextField_LastName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setBounds(20, 40, 80, 20);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_FirstName.setText(resourceMap.getString("jTextField_FirstName.text")); // NOI18N
        jTextField_FirstName.setName("jTextField_FirstName"); // NOI18N
        jTextField_FirstName.setBounds(110, 40, 179, 20);
        jLayeredPane2.add(jTextField_FirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setBounds(20, 20, 80, 20);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_PersonID.setText(resourceMap.getString("jTextField_PersonID.text")); // NOI18N
        jTextField_PersonID.setName("jTextField_PersonID"); // NOI18N
        jTextField_PersonID.setBounds(110, 20, 180, 20);
        jLayeredPane2.add(jTextField_PersonID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jLayeredPane3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jLayeredPane3.border.titleFont"))); // NOI18N
        jLayeredPane3.setName("jLayeredPane3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1ResultList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Address", "City", "State", "Zip Code"
            }
        ));
        jTable1ResultList.setName("jTable1ResultList"); // NOI18N
        jScrollPane1.setViewportView(jTable1ResultList);
        jTable1ResultList.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title1")); // NOI18N
        jTable1ResultList.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title2")); // NOI18N
        jTable1ResultList.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title3")); // NOI18N
        jTable1ResultList.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title4")); // NOI18N
        jTable1ResultList.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title5")); // NOI18N
        jTable1ResultList.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("jTable1ResultList.columnModel.title6")); // NOI18N

        jScrollPane1.setBounds(10, 20, 630, 150);
        jLayeredPane3.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.setBounds(580, 180, 50, -1);
        jLayeredPane3.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.setBounds(525, 180, 50, -1);
        jLayeredPane3.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(208, 208, 208)
                        .addComponent(jButton6)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton_Search)
                    .addComponent(jButton3)
                    .addComponent(jButton_Clear)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(31, 31, 31)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClearMouseClicked
        // TODO add your handling code here:
       org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(main.MainApp.class).getContext().getResourceMap(JFramePerson.class);
       jTextField_PersonID.setText("");
       jTextField_FirstName.setText("");
       jTextField_LastName.setText("");
       jTextField_Address.setText("");
       jTextField_City.setText("");
       jTextField_State.setText("");
       jTextField_ZipCode.setText("");
       jTextField_PersonType.setText("");

       jTable_CourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Section", "Meeting Times", "Location"
            }
        ));

}//GEN-LAST:event_jButton_ClearMouseClicked

    private void jButton_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SearchMouseClicked
        // TODO add your handling code here:
       jTextField_PersonID.setText("a");
       jTextField_FirstName.setText("b");
       jTextField_LastName.setText("c");
       jTextField_Address.setText("d");
       jTextField_City.setText("e");
       jTextField_State.setText("f");
       jTextField_ZipCode.setText("g");
       jTextField_PersonType.setText("h");

       jTable_CourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, 2, 3, 4},
                {5, 6, 6, 6},
                {3, 3, 3, 3},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Section", "Meeting Times", "Location"
            }
        ));
//        jTable_CourseList.setValueAt("aaa", 1, 1);
}//GEN-LAST:event_jButton_SearchMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1ResultList;
    private javax.swing.JTable jTable_CourseList;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_City;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_PersonID;
    private javax.swing.JTextField jTextField_PersonType;
    private javax.swing.JTextField jTextField_State;
    private javax.swing.JTextField jTextField_ZipCode;
    // End of variables declaration//GEN-END:variables

}
