/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentsSearch.java
 *
 * Created on Dec 14, 2008, 6:00:16 AM
 */

package edu.sjsu.edo08f.gui;

import edu.sjsu.edo08f.services.StudentService;
import edu.sjsu.edo08f.services.PersonService;
import edu.sjsu.edo08f.domain.Student;
import edu.sjsu.edo08f.domain.Person;
import edu.sjsu.edo08f.BeanRetriever;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author Anita
 */
public class StudentsSearch extends javax.swing.JFrame {


    public static String personType;
     public static String personField;
     public static String fieldValue;
    /** Creates new form StudentSearch */
    public StudentsSearch(String personType , String personField , String fieldValue) {
         this.personType = personType;
         this.personField = personField;
         this.fieldValue = fieldValue;
        initComponents();
    }
 public void getAttributes(ArrayList studentSearch){


     System.out.println("Array check : "+personType);
         System.out.println("Array check : "+personField);
         System.out.println("Array check : "+fieldValue);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setText("CmpE 273 - Project");

      PersonService personService = (PersonService) BeanRetriever.getBeanFactory().getBean("personService");
             List<Person> person =personService.search(personField,fieldValue);
         System.out.println(personType);
         System.out.println(personField);
         System.out.println(fieldValue);

    JFrame frame = new JFrame("List of all students ");
    String data[][] = {{"Id", "FirstName", "Last Name", "Address", "City", "State", "Zip"}};
    String col[] = {"Id", "FirstName", "Last Name", "Address", "City", "State", "Zip"};
    DefaultTableModel model = new DefaultTableModel(data,col);
    JTable table = new JTable(model);

for (Person personToBeDisplayed : person) {
   if(personToBeDisplayed.getType().toLowerCase().equals(personType.toLowerCase())){
       model.insertRow(table.getRowCount(),new Object[]{personToBeDisplayed.getId(), personToBeDisplayed.getFirstName(), personToBeDisplayed.getLastName(),personToBeDisplayed.getAddress(),personToBeDisplayed.getCity(),personToBeDisplayed.getState(),personToBeDisplayed.getZipCode()});
    }
     }



    frame.add(table);
    frame.setSize(600,300);
    frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsSearch("No Input","No Input", "No Input");

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;

    // End of variables declaration//GEN-END:variables

}